apiVersion: v1
kind: Service

metadata:
  name: ros2-backend-service

spec:
  type: NodePort

  selector:
    app: ros2-backend

  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500

    - name: rosbridge
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30909
